### PR TITLE
Don't run cov inside the qemu-chroot-y-thing

### PR DESCRIPTION
**Pull request by doismellburning**
This should speed up test runs somewhat!

### CODE REVIEW

**Comment by doismellburning** [comment]
This was overly naïve since we're running on a Travis Erlang env...

But it's a start!

**Comment by pozorvlak** [comment]
Looks good to me. The use of an Erlang VM was suggested on http://www.tomaz.me/2013/12/02/running-travis-ci-tests-on-arm.html, the rationale being

> Travis uses a dedicated set of VMs for each language and the reason for selecting a less popular one is so you don’t hog resources and further increase the wait time for other people who use a more popular language / runtime.

I'm not convinced we should be doing this, TBH.

**Comment by doismellburning** [comment]
Well I've accidentally broken the tox filtering, but this is looking more plausible otherwise...

**Comment by doismellburning** [comment]
Yep, `cov` run now takes about 1min... https://travis-ci.org/py3minepi/py3minepi/jobs/36829416

(Obviously running it with 2.7 isn't ideal, nor is my other tox breakage, but it's still sort-of-progress...)

**Comment by doismellburning** [comment]
Success!

**Comment by doismellburning** [comment]
Oh, `cov` actually passes now, guess this obsoletes #36!

**Comment by doismellburning** [comment]
So yeah, this supersedes #36 but is a wider change; you may still want to merge #36 'til things like "running cov under python 2.7" get hashed out (I'm not sure it's a _terrible_ thing, but it's certainly more questionable than the minimal fix in #36)

**Comment by ghickman** [comment]
I see no issue with running this under 2.7 given it's successfully running in the travis environment. If there's consensus from others then I'll merge it.

**Comment by doismellburning** [comment]
_tumbleweed_ :P

**Comment by doismellburning** [comment]
Thanks!

**Pull request merged**
