### PR TITLE
Delete strange ordering

### PR DESCRIPTION
**Pull request by doismellburning**
Removed some `__cmp__`s that don't seem to make sense

I wouldn't merge this yet, this is more of a proposal PR; I've not actually checked for their usage anywhere etc.!

### CODE REVIEW

**Comment by doismellburning** [comment]
I would hope this went without saying, but please, if I've missed the point / this causes subtle breakage / this is a terrible idea / $other, do let me know!

**Comment by ghickman** [comment]
@doismellburning – the only reason I could see for these `__cmp__` checks is for equality purposes but we should be using `__eq__` for that anyway. I see `Vec3` already has one but `Block` doesn't so maybe we should replace the `__cmp__` there with one?

**Comment by doismellburning** [comment]
Ah good point!

**Comment by doismellburning** [comment]
Welp, it passes! We don't yet test any higher level exampley stuff though...

**Comment by doismellburning** [comment]
Thanks to https://github.com/py3minepi/py3minepi/pull/26 there's only one strange ordering to delete!

**Comment by doismellburning** [comment]
I would rather see #37 go in before this, because y'know, breakage etc.

**Pull request merged**
