### PR TITLE
Use pre-built arm chroot to speed up test runs

### PR DESCRIPTION
**Pull request by doismellburning**
https://github.com/py3minepi/arm-chroot

### CODE REVIEW

**Comment by doismellburning** [comment]
I sure hope this works! https://travis-ci.org/py3minepi/py3minepi/builds/37159948 shows runs of about 16-17 mins, most of which seemed to be in building the chroot

**Comment by doismellburning** [comment]
https://travis-ci.org/py3minepi/py3minepi/jobs/37236446

"chroot: failed to run command `apt-get': Exec format error" :(

**Comment by doismellburning** [comment]
http://community.arm.com/groups/embedded/blog/2013/11/21/cross-compilation-for-arm is interesting reading.

I suspect I don't understand enough about what I've pulled out to the prebuild

**Comment by dbrgn** [comment]
Did you compile for ARMv6?

**Comment by doismellburning** [comment]
I don't see any compilation stage?

**Pull request closed without merging**
