### PR TITLE
Fix for repr and add unit test for event

### PR DESCRIPTION
**Pull request by hashbangstudio**
Face of cube is always an integer and entityId should always be discrete integer
So use :d instead of :2f

Add unit test of event.py

### CODE REVIEW

**Comment by doismellburning** [comment]
Would you mind splitting this please? And if you're changing the behaviour of `__repr__` could you please validate the identity (if it's not already!) - thanks!

**Comment by ghickman** [comment]
@hashbangstudio – Thanks for this but could you narrow this PR down to only add the test suite then make the rep change in another one.

**Comment by ghickman** [comment]
@hashbangstudio – Sorry to lump more on you, but could you also:
- convert the tests to pytest syntax (we're aiming to use it by default)
- remove the running code block at the bottom, we have a runner setup
- expand variable names to full words, there seems little need to shortening them

Thanks!

**Comment by hashbangstudio** [comment]
This request should now be just the test suite without repr change

**Comment by doismellburning** [comment]
Hurrah, thanks - I don't know much about pytest though, but it doesn't look like it's running this?

**Comment by hashbangstudio** [comment]
Someone might have to hit rebuild?

**Comment by dbrgn** [comment]
No. The test suite takes very long (10-20min) and there is a limit on how many tests are run per repository on Travis at the same time. We'll just have to wait.

I'm not sure if we should actually keep the Qemu stuff in Travis. Slow tests slow down development (as seen in this case) and are demotivating.

**Comment by doismellburning** [comment]
> it doesn't look like it's running this

I didn't mean "there isn't a build running" I meant "the test suite wasn't running those tests", just to clarify

**Comment by doismellburning** [comment]
(and, er, my bad, I missed https://travis-ci.org/py3minepi/py3minepi/jobs/36809350#L1521)

**Comment by ghickman** [comment]
I've pulled this branch locally and run with tox and the tests are running under 3.4 at least.

**Comment by doismellburning** [comment]
@ghickman Yeah sorry they were, I had one of your "not seeing it" moments :P

**Comment by doismellburning** [comment]
@ghickman I know you're pro the tests being pytest style, but what about accepting unittest style too, since pytest runs them, and it reduces the friction for people contributing tests?

**Comment by dbrgn** [comment]
> @ghickman I know you're pro the tests being pytest style, but what about accepting unittest style too, since pytest runs them, and it reduces the friction for people contributing tests?

The main advantage of using pytest style tests is that they're actually easier to write for the committer and maintain for the maintainers :) As long as the naming is according to PEP8, unittest style tests would be fine with me though.

**Comment by pozorvlak** [comment]
Is the time taken to run CI tests really slowing people down? How many people are working on this full-time or close to? [I've had very little time to contribute for the last week or two, which is why my
"contributions" have been limited to bikeshedding]. I think it's worth having a slower CI stage\* that actually tests the code in the environment we care about (because if we don't then we'll get environment-skew breakages sooner or later, and those are an utter pain to track down and fix), but that we shouldn't run a full Qemu simulation test as part of the ordinary edit-test cycle.
- I'm now flashing back to the year I spent doing C++ compiler development, where the test suite took three hours to run _even after being distributed over a 12-box cluster_. And indeed the job before that, where the linker stage alone took 15 minutes. Oh sweet summer child, what do you know of slow builds?

**Comment by doismellburning** [comment]
> Is the time taken to run CI tests really slowing people down?

Yes, check out https://travis-ci.org/py3minepi/py3minepi/builds - there was a 2-3h block of solid test runs last night / this morning that was mildly inconvenient

That said, I'm still kinda pro testing on every commit, in the current fashion; I just want to speed it up more - e.g. by turning the qemu stage into a single package or something

**Comment by dbrgn** [comment]
Good idea, maybe we could convert the output from the debian bootstrap thing into an image?

**Comment by pozorvlak** [comment]
Good idea. Travis's [built-in caching](﻿﻿http://docs.travis-ci.com/user/caching/) is a paid feature, but I'd be
happy to host an image file. The slightly tricky thing would be
regenerating the image if the dependencies have changed.

**Comment by ghickman** [comment]
@hashbangstudio – Thanks for this!

**Comment by doismellburning** [comment]
@ghickman Could you ensure that your merge commits have sensible messages please? https://github.com/py3minepi/py3minepi/commit/84ff461bae2bbe2c8a2e9ee22cecec7c32754a9c does nothing with `repr` at all. Thanks.

**Comment by ghickman** [comment]
Sure thing.

**Pull request merged**
