### PR TITLE
Run flake8 as part of the test suite

### PR DESCRIPTION
**Pull request by ghickman**
This change codifies the usage of the `flake8` command in our test suite.

### CODE REVIEW

**Comment by doismellburning** [comment]
Whack it in the Travis matrix?

**Comment by dbrgn** [comment]
Not necessary, the py.test `--pep8` option already covers this. Try it - change something to non-pep8-conforming and run the test suite using tox.

**Comment by dbrgn** [comment]
Actually, it just checks PEP8, but not pyflakes. But I think that's enough. And also keep in mind that just running this additional check in Travis results in +10-15 minutes of testing time.

**Comment by ghickman** [comment]
@dbrgn – Why will this result in this kind of increase? Travis isn't going to be building a new Qemu environment for the flake8 portions.

**Comment by dbrgn** [comment]
> @dbrgn – Why will this result in this kind of increase? Travis isn't going to be building a new Qemu environment for the flake8 portions.

Yes it will. Every part of the matrix is a separate build.

**Comment by ghickman** [comment]
@dbrgn – Oh yes I see, sorry! That's frustrating…

**Comment by doismellburning** [comment]
Stick the flake8 in tox at least; I don't see the point in closing this

**Comment by ghickman** [comment]
Ok sure, will update the PR

**Comment by dbrgn** [comment]
That's a good idea.

Don't forget to exclude the legacy API, it won't be PEP8 conform regarding casing of method names.

**Comment by doismellburning** [comment]
Two things that might mitigate it slightly
1. I can't find a citation but iirc we get two workers, so in the case of an isolated PR this takes us from 3 to 4 builds, so no real overall extension (I accept this is slightly weak logic)
2. I believe I'm right in thinking we don't need the qemu logic for flake8/cov; we could probably lob some logic _somewhere_ (haven't really figured out where) not to kick that all off for those builds

**Comment by dbrgn** [comment]
Maybe we could run qemu in only one of the workers with Python 3.2, while all the other workers ignore the integration tests.

**Comment by ghickman** [comment]
I believe you don't get to control how the workers are used, you get to use N from the available pool. However having the matrix run different scripts might be possible.

**Comment by doismellburning** [comment]
> However having the matrix run different scripts might be possible.

I don't mean that (because I don't believe you can) - I'm only thinking something superhacky like defining `WITH_QEMU`... (I'm'a go try that now)

**Comment by dbrgn** [comment]
> I'm only thinking something superhacky like defining WITH_QEMU

I don't think that's too hacky. That's the approach I would choose :) And then you can decide in the `.travis-ci.sh` script whether to init the environment or not.

**Comment by dbrgn** [comment]
Maybe we could name it `WITH_INTEGRATION` though.

**Comment by doismellburning** [comment]
https://github.com/py3minepi/py3minepi/pull/35

**Comment by ghickman** [comment]
This PR is now blocked by #35.

**Comment by ghickman** [comment]
I'll merge master in when we've dealt with #35.

**Comment by doismellburning** [comment]
You might want/need to set flake8 to run under 2.7 for now FYI (c.f. #35 / 1df8aa35909295ba6b66ef66c2530dbb8613d105)

**Comment by doismellburning** [comment]
That'll be a "need" then ;)

**Comment by ghickman** [comment]
Nailed it…

**Comment by doismellburning** [comment]
Huzzah :)

**Comment by doismellburning** [comment]
Yay! Can you fix the merge conflict though please?

**Comment by doismellburning** [comment]
(Ahem, that would, er, be the merge conflict that I introduced....sorry!)

**Comment by ghickman** [comment]
Merged… and now we wait!

**Comment by doismellburning** [comment]
So yeah, sorry for the merge conflict!

**Pull request merged**
